import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const $=s=>document.querySelector(s),scene=new T.Scene();scene.background=new T.Color('#d6dfe1');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;document.body.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.08,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=15;controls.minDistance=1;controls.maxPolarAngle=Math.PI*.49;
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;scene.environmentIntensity=.42;room.dispose();pmrem.dispose();
scene.add(new T.HemisphereLight(0xe3efff,0x83705c,1.1));const sun=new T.DirectionalLight(0xffefd6,3.1);sun.position.set(-3,7,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:.1,far:25});sun.shadow.normalBias=.012;sun.shadow.bias=-.0001;scene.add(sun);
let model,selected=null,items=[];const initial=new Map(),ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0),hit=new T.Vector3();
function view(){const mobile=innerWidth<700;camera.position.set(mobile?7:5.4,mobile?6:3.8,mobile?8:6.9);controls.target.set(-.3,.8,-.15);camera.clearViewOffset();if(mobile)camera.setViewOffset(innerWidth,innerHeight,0,innerHeight*.17,innerWidth,innerHeight);else camera.setViewOffset(innerWidth,innerHeight,150,0,innerWidth,innerHeight);controls.update();}
function select(o){selected=o;$('#objects').value=o?.uuid||'';$('#state').textContent=o?o.name+' · tocar el piso para mover':'Seleccionar un mueble para editar';}
try{const gltf=await new GLTFLoader().loadAsync('terraza.glb');model=gltf.scene;scene.add(model);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material?.transmission>0){o.castShadow=false;o.material.envMapIntensity=1;}}if(o.userData.editable===true){items.push(o);initial.set(o.uuid,{p:o.position.clone(),q:o.quaternion.clone()});const option=document.createElement('option');option.value=o.uuid;option.textContent=o.name;$('#objects').append(option);}});view();select(null);window.TERRAZA={items,model,ready:true};}catch(e){$('#state').textContent='No se pudo cargar el modelo. Recargá para intentar nuevamente.';console.error(e);}
$('#objects').onchange=e=>select(items.find(o=>o.uuid===e.target.value));$('#rotate').onclick=()=>{if(selected)selected.rotateZ(Math.PI/4);};
$('#hide').onclick=()=>{if(selected){selected.visible=false;select(null);}};$('#reset').onclick=()=>{for(const o of items){const x=initial.get(o.uuid);o.position.copy(x.p);o.quaternion.copy(x.q);o.visible=true;}select(null);};$('#view').onclick=view;$('#compare').onclick=()=>$('#ref').classList.add('open');$('#close').onclick=()=>$('#ref').classList.remove('open');
let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!model||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;pointer.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(items.filter(o=>o.visible),true);if(hits.length){let o=hits[0].object;while(o&&!items.includes(o))o=o.parent;if(o){select(o);return;}}
if(selected&&ray.ray.intersectPlane(plane,hit)){const local=model.worldToLocal(hit.clone());if(Math.abs(local.x)<2.8&&Math.abs(local.z)<1.45){const parentPoint=selected.parent.worldToLocal(hit.clone());selected.position.x=parentPoint.x;selected.position.y=parentPoint.y;$('#state').textContent='Posición actualizada';}else $('#state').textContent='Elegir un punto dentro de la terraza';}});
window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();view();});renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
